payload:
- DOMAIN,software.download.prss.microsoft.com
- DOMAIN,outlook-1.cdn.office.net
- DOMAIN,s0.2mdn.net
- DOMAIN,static.2mdn.net
- DOMAIN,statics.teams.cdn.office.net
- DOMAIN,uci.cdn.office.net
- DOMAIN,wscont2.apps.microsoft.com
- DOMAIN,wscont1.apps.microsoft.com
- DOMAIN,officecdn.microsoft.com
- DOMAIN,officecdn.microsoft.com.edgesuite.net