name: Sync to GitLab

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Update Public Library]
    types: [completed]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to GitLab
        env:
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_PAT }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL#https://}"
          git push gitlab --all --force
          git push gitlab --tags --force

      - name: Delete old workflow runs
        uses: Suyunmeng/delete-old-workflow-runs@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600
